# SkyWars Clean Architecture Configuration

# Database Configuration
database:
  mysql:
    host: "localhost"
    port: 3306
    database: "skywars"
    username: "root"
    password: "password"
    # HikariCP Connection Pool Settings
    pool:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  timeout: 2000
  # Connection Pool Settings
  pool:
    max-total: 8
    max-idle: 8
    min-idle: 0

# Cache Settings
cache:
  # Time in seconds to keep data in Redis
  user-cache-ttl: 1800  # 30 minutes
  # Auto-save interval in seconds
  auto-save-interval: 300  # 5 minutes

# Game Settings
game:
  # Default player stats
  default-stats:
    kills: 0
    deaths: 0
    wins: 0
    losses: 0
    coins: 100
  
  # Kill rewards
  rewards:
    kill-coins: 10
    win-coins: 50

# Messages
messages:
  prefix: "&8[&bSkyWars&8] &r"
  player-not-found: "&cPlayer not found!"
  stats-format: "&6Stats for &e{player}&6: &7Kills: &a{kills} &7Deaths: &c{deaths} &7K/D: &e{kd} &7Coins: &6{coins}"
  database-error: "&cDatabase error occurred. Please try again later."
  cache-error: "&cCache error occurred. Using database fallback."
